### ISSUE TITLE
Regression in libgcc, missing functionality of libgcc1 4.9.2

### ISSUE THREAD

**Issue by dspiatkowski** [bitwiseworks/gcc-os2#18]
**Describe the bug**
Attempted to upgrade my working gcc 4.9.2 configuration. Executed through ANPM, the process failed, found the following in the anpm.log:

=== START ===
----------[ 10 Feb 2020 19:53:25 ]----------
Executing: @python G:\UTIL\ANPM\scripts\yum_update.py gcc
Enabling temporary repository arcanoae-exp
Package libgcc1 is obsoleted by libgcc, but obsoleting package does not provide for requirements
Package libgcc1 is obsoleted by libgcc, but obsoleting package does not provide for requirements
Package libgcc1 is obsoleted by libgcc, but obsoleting package does not provide for requirements
Package libgcc1 is obsoleted by libgcc, but obsoleting package does not provide for requirements
Package libgcc1 is obsoleted by libgcc, but obsoleting package does not provide for requirements
Package libgcc1 is obsoleted by libgcc, but obsoleting package does not provide for requirements
Package libgcc1 is obsoleted by libgcc, but obsoleting package does not provide for requirements
Package libgcc1 is obsoleted by libgcc, but obsoleting package does not provide for requirements
Package libgcc1 is obsoleted by libgcc, but obsoleting package does not provide for requirements
Running Transaction Check
YumRPMCheckError(): [u'ERROR with transaction check vs depsolve:', 'libgcc1 is needed by (installed) libaio-0.0.1-5.oc00.pentium4', 'libgcc1 is needed by (installed) libvncserver-0.9.10-4.oc00.pentium4', 'libgcc1 is needed by (installed) libidl-0.8.14-6.oc00.pentium4', u'Please report this error at http://yum.baseurl.org/report']
Error: ERROR with transaction check vs depsolve:libgcc1 is needed by (installed) libaio-0.0.1-5.oc00.pentium4libgcc1 is needed by (installed) libvncserver-0.9.10-4.oc00.pentium4libgcc1 is needed by (installed) libidl-0.8.14-6.oc00.pentium4Please report this error at http://yum.baseurl.org/report
YumRPMCheckError()
Return code: 0
=== STOP ===

Looks like there are a number of other RPM packages which I installed on my system that require functionality provided in libgcc1, unfortunately that functionality is no longer available in libgcc that is part of 9.2.0 release.

**Comment by SilvanScherrer** [comment]
This is not really a bug. It's more wrong rpm files. we know that vncserver and libidl are done wrong. I already told the author to redo them. If he will who knows. We can't unfortunately do them all. So your only choice here is to remove the vncserver and libidl and update gcc. If this it not possible you need to wait until the author reacts.
I leave it open until the author fixed it.

**Comment by dspiatkowski** [comment]
Hi Silvan!
Alright, that sure makes sense. While conceptually I suspected something was up along those lines I really had no idea how to even attempt to debug this on my own, which is why it ended up here in the GCC queue. Thank you for investigating this.

I am curious about something though, would something like libgcc-fwd package not be able to address such a requirement where another package relies on a different DLL (in this case an older 4.9.2 one) by simply re-pointing that call to a new 9.2.x dll instead? I always thought that was the whole purpose of the forwarded DLLs.

**Comment by SilvanScherrer** [comment]
You mix dll names with package names. And as the wrong rpm wants a package with libgcc1 as name it cant work, as there is no such package anymore. It was by accident named like that in gcc 4.9.2. If the package would want /@unixroot/lib/gcc1.dll then rpm automatically searches packages with this name and would find the forwarder package.
And as we didnt provide any such wrong package we decided to rename libgcc1 to what it is on Fedora. As this is the guideline we follow.

**Comment by SilvanScherrer** [comment]
it seems like most if not all of the wrong packages got updated. So I close this issue. If something is not working with the new packages, please ask the authors of them.
