### ISSUE TITLE
The build-script example does not work out-of-the-paste

### ISSUE THREAD

**Issue by rdpe** [bitwiseworks/gcc-os2#23]
The build-script at:
https://github.com/bitwiseworks/gcc-os2/wiki/Developers#building-gcc
tries to run 'master/autogen.sh' while the curdir is assumed 'gcc' (the toplevel dir).
Should be something like: 'cd master && ./autogen.sh && cd -' ?

Very cool to have this updated GCC btw !
Ben.

**Comment by dmik** [comment]
Yes, you are right, thanks, fixed it. (Didn't use `cd -` to not depend on PWD/OLDPWD).
