### ISSUE TITLE
Cannot start Firefox 45.9.0 with libgcc 9.2.0-3 or 9.2.0-4

### ISSUE THREAD

**Issue by LewisR** [bitwiseworks/gcc-os2#26]
Unfortunately, when attempting to start the last Firefox build submitted to AN (firefox-45.9.0-2), the exe exits immediately, with no TRP file. Downgrading 9.2.0-4 (or 9.2.0-3) gcc packages to 9.2.0-2 allows the program to start. I have installed libc-debuginfo, firefox-debug, gcc-debuginfo. Luckily, this package was not widely distributed, However, it is unknown what other applications may be similarly affected with the new gcc build.

I'm happy to try to get some useful data out of this, but right now, all I get is a quick program exit (almost immediately). The TRP file (with exceptq=Z) is a standard process termination notice, and as exceptq traps, it's hard to know what may be useful.

Edit2: Confirming my original findings. 9.2.0-3 does not work, either. Attempting (again) to gather debug info.

**Comment by dmik** [comment]
Not enough details. Did you try the latest Firefox from https://github.com/bitwiseworks/mozilla-os2/releases/tag/FIREFOX_45_9_0esr_RELEASE_OS2_GA2? Here it works perfectly well with gcc 9.2.0-4 installed.

**Comment by LewisR** [comment]
TRP attached from https://github.com/bitwiseworks/mozilla-os2/releases/tag/FIREFOX_45_9_0esr_RELEASE_OS2_GA2. Here it doesn't work perfectly, and fails exactly the same way the -2 release does with either libgcc 9.2.0-3 or 9.2.0-4.
[0043_01.TRP.txt](https://github.com/bitwiseworks/gcc-os2/files/4637658/0043_01.TRP.txt)

**Comment by LewisR** [comment]
We managed to track this down to a mismatch in libcn0.dll and stdcpp6.dll.

Both libstdc++-9.2.0-3 and 9.2.0-4 appear to require libc-0.1.4-1. This is the same issue we've seen [here](https://trac.netlabs.org/rpm/ticket/257) and [here](https://trac.netlabs.org/rpm/ticket/259).

Not wanting to ship a lot of (any, actually) experimental stuff in ArcaOS 5.0.5 has brought about this unfortunate situation.

**Comment by dmik** [comment]
Okay, good to know that you manged that. LIBC 0.4.1 seems to run quite fine here (no known regressions) and yes — they come in pair with GCC 9 (it contains a lot of fixes for it). You either use both or none.
